commands:
  hub:
    server: hub
    permission: ""
  mcatlas:
    server: mcatlas
    permission: ""
  mcplots:
    server: mcplots
    permission: ""
  skyblock:
    server: skyblock
    permission: ""
  infinite:
    server: infinite
    permission: ""
  build:
    server: build
    permission: ruinscraft.command.build
  dev:
    server: dev
    permission: ruinscraft.command.dev
