commands:
  hub:
    server: hub
    permission: ""
  mcatlas:
    server: mcatlas
    permission: ""
  mcplots:
    server: mcplots
    permission: ""
  buildcomp:
    server: buildcomp
    permission: ""
  build:
    server: build
    permission: ruinscraft.command.build
